# Generated by Django 5.2 on 2025-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
