# Generated by Django 5.2 on 2025-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_router_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='download_speed',
            field=models.CharField(default='No limit', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('data_plan', 'Data Plan')], default='hotspot', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='upload_speed',
            field=models.CharField(default='No limit', max_length=255),
        ),
    ]
