# Generated by Django 5.1 on 2025-04-29 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_router_identity_router_secrete_alter_router_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default='30', max_length=100),
        ),
    ]
