# Generated by Django 5.1 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_package_created_at_package_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(default='30 days', max_length=100),
        ),
    ]
