# Generated by Django 5.2 on 2025-04-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_package_download_speed_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
