# Generated by Django 5.1 on 2025-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_alter_package_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='No address', max_length=255),
        ),
    ]
