# Generated by Django 5.1 on 2025-05-04 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPAccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payment_expiry', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('failed_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isp_account_payments', to='user_dashboard.ispprovider')),
            ],
        ),
    ]
