# Generated by Django 5.2 on 2025-04-13 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
