# Generated by Django 5.2 on 2025-04-13 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_billing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
