# Generated by Django 5.2 on 2025-04-14 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_start', models.DateField(blank=True, null=True)),
                ('router_password', models.CharField(max_length=255)),
                ('package_name', models.CharField(max_length=255)),
                ('router_name', models.CharField(max_length=255)),
                ('due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='due',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='package_start',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='router_name',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='router_password',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='isp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user_dashboard.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='isp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='user_dashboard.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('isp', 'ISP')], default='user', max_length=50),
        ),
    ]
