# Generated by Django 5.2 on 2025-04-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0010_client_remove_detail_due_remove_detail_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='user_dashboard.package'),
            preserve_default=False,
        ),
    ]
