# Generated by Django 5.2 on 2025-04-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_client_isp_alter_client_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='ISPProvider',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='status',
        ),
        migrations.AddField(
            model_name='detail',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
