# Generated by Django 5.2 on 2025-04-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0013_rename_company_ispprovider_remove_detail_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='address',
        ),
    ]
