# Generated by Django 5.2 on 2025-04-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0014_remove_detail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispprovider',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='isp', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
