# Generated by Django 5.2 on 2025-04-16 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0017_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user_dashboard.ispprovider'),
        ),
        migrations.AlterField(
            model_name='ispprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isp_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
